name: Build Releases

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  publish:
    name: Build ${{ matrix.asset_name }}
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - script: build.bat
            artifact_name: breeze-cl
            asset_name: breeze
          - script: buildw.bat
            artifact_name: breezew-cl
            asset_name: breeze-terminal
    steps:
    - uses: actions/checkout@v4
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.13.0
    - name: Build Release Files
      shell: cmd
      run: ${{ matrix.script }}
    - name: Upload built files release
      uses: svenstaro/upload-release-action@2.9.0
      with:
        file: ${{ matrix.artifact_name }}.exe
        asset_name: ${{ matrix.asset_name }}-v$tag.exe
    - name: Upload license to release
      uses: svenstaro/upload-release-action@2.9.0
      with:
        file: LICENSE
        overwrite: true
